<template>
  <div>
    <div class="page-header"><div><h1>Billing Readiness for Scheduled Procedures</h1><div class="desc">Cross-check payment status before confirming theatre bookings.</div></div></div>
    <div class="card">
      <table class="data-table">
        <thead><tr><th>Patient</th><th>Package</th><th>Total</th><th>Outstanding Milestone</th><th>Cleared to Proceed?</th></tr></thead>
        <tbody>
          <tr v-for="pp in plans" :key="pp.id">
            <td class="cell-strong">{{ pp.patient_name }}</td>
            <td class="cell-muted">{{ pp.package }}</td>
            <td>{{ fmtNaira(pp.total_cost) }}</td>
            <td>
              <template v-if="unpaidOf(pp)">{{ unpaidOf(pp).label }} — <StatusBadge :status="unpaidOf(pp).status" /></template>
              <template v-else>—</template>
            </td>
            <td><Badge :tone="unpaidOf(pp) ? 'amber' : 'green'">{{ unpaidOf(pp) ? 'Hold' : 'Cleared' }}</Badge></td>
          </tr>
        </tbody>
      </table>
      <div v-if="!plans.length" style="padding:20px;"><EmptyState icon="cash" title="No payment plans yet" description="Payment plans generated by Doctor will appear here." /></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { fmtNaira } from '~/composables/useFormat'

const supabase = useSupabaseClient()
const plans = ref<any[]>([])

await useAsyncData('billing-readiness-page', async () => {
  const { data } = await supabase.from('payment_plans').select('*, patient_names(full_name), payment_milestones(*)')
  plans.value = (data || []).map((pp: any) => ({ ...pp, patient_name: pp.patient_names?.full_name || 'Unknown' }))
  return true
})

function unpaidOf(pp: any) {
  return (pp.payment_milestones || []).find((m: any) => m.status !== 'Paid')
}
</script>
