<template>
  <div class="clerking-page">
    <div class="page-header"><div><h1>Initial Clinical Clerking</h1><div class="desc">Complete this once at first clinical contact. Repeat observations belong in Patient Vitals.</div></div><div class="page-actions"><ClinicalPatientFinder v-model="patientId" allow-walk-in :initial-walk-in-open="route.query.walkIn === '1'" @selected="selectPatient" /></div></div>
    <div v-if="!patientId" class="card card-pad"><EmptyState icon="user" title="Select or register a patient" description="Use the finder above. Walk-in patients can be registered and clerked immediately." /></div>
    <form v-else class="card card-pad" @submit.prevent="save">
      <div class="form-section"><span class="section-kicker">Patient</span><b>{{ patientName || patientId }}</b></div>
      <div class="form-section"><span class="section-kicker">Medical history</span><div class="form-row"><div class="field"><label>Known conditions</label><textarea v-model="medical.conditions" class="input" rows="2" placeholder="Hypertension, diabetes, asthma, or none known" /></div><div class="field"><label>Allergies</label><textarea v-model="medical.allergies" class="input" rows="2" placeholder="Drug, food, latex, or none known" /></div></div><div class="form-row"><div class="field"><label>Current medicines / supplements</label><textarea v-model="medical.medicines" class="input" rows="2" /></div><div class="field"><label>Past surgery / admissions</label><textarea v-model="medical.surgery" class="input" rows="2" /></div></div></div>
      <div class="form-section"><span class="section-kicker">Fertility history</span><div class="form-row"><div class="field"><label>Trying to conceive (months)</label><input v-model="fertility.tryingMonths" class="input" type="number" min="0" /></div><div class="field"><label>Previous treatment</label><select v-model="fertility.previousTreatment" class="input"><option>Not asked</option><option>None</option><option>Ovulation induction</option><option>IUI</option><option>IVF / ICSI</option><option>Frozen embryo transfer</option><option>Other</option></select></div></div><div class="form-row"><div class="field"><label>Relevant reproductive history</label><textarea v-model="fertility.history" class="input" rows="3" placeholder="Pregnancy history, menstruation/semen history, prior outcomes, infection, surgery, partner context…" /></div><div class="field"><label>Fertility goals / concerns</label><textarea v-model="fertility.goals" class="input" rows="3" /></div></div></div>
      <div class="field"><label>Clinician / nurse notes</label><textarea v-model="notes" class="input" rows="3" placeholder="Information reported, counselling, risks identified, or escalation." /></div>
      <div class="form-actions"><NuxtLink :to="`/nurse/vitals?patient=${patientId}`" class="btn btn-secondary">Record vitals</NuxtLink><button class="btn btn-primary" :disabled="saving"><Icon name="check-circle" :size="13" /> {{ saving ? 'Saving…' : 'Save initial clerking' }}</button></div>
    </form>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useProfile } from '~/composables/useAuth'
import { useToast } from '~/composables/useToast'
const route=useRoute(); const supabase=useSupabaseClient(); const profile=useProfile(); const {toast}=useToast(); const patientId=ref(typeof route.query.patient==='string'?route.query.patient:''); const patientName=ref(''); const saving=ref(false)
const medical=reactive({conditions:'',allergies:'',medicines:'',surgery:''}); const fertility=reactive({tryingMonths:'',previousTreatment:'Not asked',history:'',goals:''}); const notes=ref('')
function selectPatient(entry:any){patientName.value=entry.full_name}
async function save(){if(!patientId.value||!profile.value)return; saving.value=true; const {error}=await supabase.from('patient_initial_assessments').insert({patient_id:patientId.value,assessed_by:profile.value.id,medical_history:{...medical},fertility_history:{...fertility,trying_months:fertility.tryingMonths===''?null:Number(fertility.tryingMonths)},notes:notes.value.trim()||null}); saving.value=false; if(error)return toast(error.message,'warn'); toast('Initial clerking saved to the patient record.','success')}
</script>
<style scoped>.clerking-page{max-width:1050px;margin:auto}.page-actions{width:min(700px,100%)}.form-section{border-bottom:1px solid var(--border);margin-bottom:18px;padding-bottom:14px}.section-kicker{display:block;color:var(--blue-600);font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px}.form-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}@media(max-width:700px){.page-actions{width:100%;margin-top:10px}.form-actions{justify-content:stretch}.form-actions>*{flex:1;text-align:center}}</style>
