<template>
  <div><div class="page-header"><div><h1>Inpatients & Ward Rounds</h1><div class="desc">Admissions, current ward status, and round documentation.</div></div><div class="page-actions"><button class="btn btn-primary" @click="showAdmit=true"><Icon name="plus" :size="13" /> Admit patient</button></div></div>
    <div class="card"><div class="card-header"><h3>Current admissions</h3><Badge tone="blue">{{ admissions.length }}</Badge></div><div v-if="!admissions.length" class="card-pad"><EmptyState icon="bed" title="No active admissions" description="Admitted patients will appear here for ward-round documentation." /></div><div v-for="admission in admissions" :key="admission.id" class="list-row"><Avatar :name="admission.patient_name" :size="32" /><div><div class="main-txt">{{ admission.patient_name }}</div><div class="sub-txt">{{ admission.reason }} · {{ admission.ward || 'Ward not set' }}{{ admission.bed_label ? ` · ${admission.bed_label}` : '' }}</div></div><div class="side flex gap-8"><StatusBadge :status="admission.status" /><button class="btn btn-secondary btn-sm" @click="openRound(admission)">Ward round</button><button v-if="role !== 'visiting_doctor'" class="btn btn-secondary btn-sm" @click="discharge(admission)">Discharge</button></div></div></div>
    <Modal v-model="showAdmit" title="Admit patient"><ClinicalPatientFinder v-model="admit.patientId" /><div class="field" style="margin-top:12px"><label>Reason for admission *</label><textarea v-model="admit.reason" class="input" rows="3" /></div><div class="form-row"><div class="field"><label>Ward</label><input v-model="admit.ward" class="input" placeholder="e.g. Fertility ward" /></div><div class="field"><label>Bed</label><input v-model="admit.bed" class="input" placeholder="e.g. F-03" /></div></div><template #footer><button class="btn btn-secondary" @click="showAdmit=false">Cancel</button><button class="btn btn-primary" :disabled="saving" @click="admitPatient">Admit</button></template></Modal>
    <Modal v-model="showRound" title="Document ward round"><p class="cell-muted" style="margin-bottom:10px">{{ selected?.patient_name }}</p><div class="field"><label>Subjective</label><textarea v-model="round.subjective" class="input" rows="2" /></div><div class="field"><label>Objective</label><textarea v-model="round.objective" class="input" rows="2" /></div><div class="field"><label>Assessment</label><textarea v-model="round.assessment" class="input" rows="2" /></div><div class="field"><label>Plan</label><textarea v-model="round.plan" class="input" rows="2" /></div><template #footer><button class="btn btn-secondary" @click="showRound=false">Cancel</button><button class="btn btn-primary" :disabled="saving" @click="saveRound">Save round</button></template></Modal>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useProfile } from '~/composables/useAuth'
import { useToast } from '~/composables/useToast'
const props=defineProps<{role:'doctor'|'matron'|'nurse'|'visiting_doctor'}>(); const supabase=useSupabaseClient();const profile=useProfile();const {toast}=useToast();const admissions=ref<any[]>([]);const showAdmit=ref(false);const showRound=ref(false);const saving=ref(false);const selected=ref<any>(null);const admit=reactive({patientId:'',reason:'',ward:'',bed:''});const round=reactive({subjective:'',objective:'',assessment:'',plan:''})
async function load(){const {data,error}=await supabase.from('inpatient_admissions').select('*,patient_names(full_name)').eq('status','Admitted').order('admitted_at',{ascending:false});if(error)return toast(error.message,'warn');admissions.value=(data||[]).map((a:any)=>({...a,patient_name:a.patient_names?.full_name||a.patient_id}))} await load()
async function admitPatient(){if(!admit.patientId||!admit.reason.trim()||!profile.value)return toast('Select a patient and enter the reason for admission.','warn');saving.value=true;const {error}=await supabase.from('inpatient_admissions').insert({patient_id:admit.patientId,reason:admit.reason.trim(),ward:admit.ward||null,bed_label:admit.bed||null,admitted_by:profile.value.id,attending_provider_id:props.role==='visiting_doctor'?profile.value.id:null});saving.value=false;if(error)return toast(error.message,'warn');showAdmit.value=false;Object.assign(admit,{patientId:'',reason:'',ward:'',bed:''});await load();toast('Patient admitted.','success')}
function openRound(admission:any){selected.value=admission;Object.assign(round,{subjective:'',objective:'',assessment:'',plan:''});showRound.value=true}
async function saveRound(){if(!selected.value||!profile.value)return;saving.value=true;const {error}=await supabase.from('ward_rounds').insert({admission_id:selected.value.id,documented_by:profile.value.id,...round});saving.value=false;if(error)return toast(error.message,'warn');showRound.value=false;toast('Ward round saved.','success')}
async function discharge(admission:any){const {error}=await supabase.from('inpatient_admissions').update({status:'Discharged',discharged_at:new Date().toISOString()}).eq('id',admission.id);if(error)return toast(error.message,'warn');await load();toast('Patient discharged.','success')}
</script>
