-- Complete document identity, reciprocal spouse links, and receptionist-safe
-- portal-login visibility. Safe to run more than once.

begin;
set local lock_timeout = '5s';

-- Information used on laboratory reports, invoices, receipts, letters, and
-- other official documents generated by the application.
alter table public.clinic_settings add column if not exists clinic_tagline text;
alter table public.clinic_settings add column if not exists company_phone_alt text;
alter table public.clinic_settings add column if not exists company_email text;
alter table public.clinic_settings add column if not exists company_website text;
alter table public.clinic_settings add column if not exists city text;
alter table public.clinic_settings add column if not exists state text;
alter table public.clinic_settings add column if not exists country text default 'Nigeria';
alter table public.clinic_settings add column if not exists postal_code text;
alter table public.clinic_settings add column if not exists registration_number text;
alter table public.clinic_settings add column if not exists tax_identification_number text;
alter table public.clinic_settings add column if not exists laboratory_license_number text;
alter table public.clinic_settings add column if not exists laboratory_director_name text;
alter table public.clinic_settings add column if not exists laboratory_director_title text;
alter table public.clinic_settings add column if not exists report_footer text;

-- Keep this browser-run migration independent of migration history: these
-- report audit fields may already exist from the preceding report migration.
alter table public.lab_results add column if not exists updated_at timestamptz;
alter table public.lab_results add column if not exists amended_at timestamptz;
alter table public.lab_results add column if not exists amended_by_profile_id uuid references public.profiles(id) on delete set null;
alter table public.lab_results add column if not exists amendment_reason text;
update public.lab_results set updated_at = coalesce(updated_at, created_at, now()) where updated_at is null;
alter table public.lab_results alter column updated_at set default now(), alter column updated_at set not null;
drop trigger if exists lab_results_set_updated_at on public.lab_results;
create trigger lab_results_set_updated_at before update on public.lab_results
for each row execute function public.set_updated_at();

-- A new patient can be registered alone, linked to an existing registered
-- partner, or registered together with a new partner. Both database records
-- are created and linked in one transaction.
create or replace function public.register_new_patient_with_partner(
  p_first text,
  p_last text,
  p_dob date,
  p_sex text,
  p_phone text,
  p_email text,
  p_address text,
  p_ec_name text,
  p_ec_relationship text,
  p_ec_phone text,
  p_referral_source text,
  p_existing_spouse_id text default null,
  p_new_spouse jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  primary_id text;
  partner_id text;
  partner_created boolean := false;
  primary_name text;
  partner_name text;
  existing_partner_link text;
begin
  if public.current_app_role() not in ('receptionist', 'admin_manager') then
    raise exception 'not authorized to register patients' using errcode = '42501';
  end if;
  if nullif(btrim(coalesce(p_existing_spouse_id, '')), '') is not null and p_new_spouse is not null then
    raise exception 'choose either an existing spouse or a new spouse, not both';
  end if;

  select r.mrn into primary_id
  from public.register_new_patient(
    p_first, p_last, p_dob, p_sex, p_phone, p_email, p_address,
    p_ec_name, p_ec_relationship, p_ec_phone, p_referral_source
  ) r
  limit 1;

  if p_new_spouse is not null then
    if nullif(btrim(p_new_spouse ->> 'first'), '') is null
       or nullif(btrim(p_new_spouse ->> 'last'), '') is null
       or nullif(btrim(p_new_spouse ->> 'dob'), '') is null then
      raise exception 'new spouse first name, surname, and date of birth are required';
    end if;

    select r.mrn into partner_id
    from public.register_new_patient(
      p_new_spouse ->> 'first',
      p_new_spouse ->> 'last',
      (p_new_spouse ->> 'dob')::date,
      coalesce(nullif(p_new_spouse ->> 'sex', ''), 'Unknown'),
      p_new_spouse ->> 'phone',
      p_new_spouse ->> 'email',
      coalesce(nullif(p_new_spouse ->> 'address', ''), p_address),
      p_first || ' ' || p_last,
      'Spouse / Partner',
      p_phone,
      p_referral_source
    ) r
    limit 1;
    partner_created := true;
  elsif nullif(btrim(coalesce(p_existing_spouse_id, '')), '') is not null then
    partner_id := btrim(p_existing_spouse_id);
    select bd.spouse_patient_id into existing_partner_link
    from public.bio_details bd
    where bd.patient_id = partner_id;
    if not found then raise exception 'selected spouse patient was not found'; end if;
    if existing_partner_link is not null and existing_partner_link <> primary_id then
      raise exception 'selected patient is already linked to another spouse';
    end if;
  end if;

  if partner_id is not null then
    select pn.full_name into primary_name from public.patient_names pn where pn.patient_id = primary_id;
    select pn.full_name into partner_name from public.patient_names pn where pn.patient_id = partner_id;

    update public.bio_details
    set spouse_patient_id = partner_id,
        spouse = coalesce(spouse, '{}'::jsonb) || jsonb_build_object('name', partner_name, 'patientId', partner_id)
    where patient_id = primary_id;

    update public.bio_details
    set spouse_patient_id = primary_id,
        spouse = coalesce(spouse, '{}'::jsonb) || jsonb_build_object('name', primary_name, 'patientId', primary_id)
    where patient_id = partner_id;

    perform public.log_audit_event('Linked Patient Spouses', primary_id || ' <-> ' || partner_id);
  end if;

  return jsonb_build_object(
    'patient_id', primary_id,
    'spouse_patient_id', partner_id,
    'spouse_created', partner_created
  );
end;
$$;

revoke all on function public.register_new_patient_with_partner(text,text,date,text,text,text,text,text,text,text,text,text,jsonb) from public, anon;
grant execute on function public.register_new_patient_with_partner(text,text,date,text,text,text,text,text,text,text,text,text,jsonb) to authenticated;

-- Repair safe one-sided legacy links when the target is not already linked.
with reverse_links as (
  select source.patient_id as source_patient_id,
         source.spouse_patient_id as target_patient_id,
         row_number() over (partition by source.spouse_patient_id order by source.updated_at desc, source.patient_id) as priority
  from public.bio_details source
  where source.spouse_patient_id is not null
)
update public.bio_details target
set spouse_patient_id = reverse_links.source_patient_id
from reverse_links
where reverse_links.priority = 1
  and target.patient_id = reverse_links.target_patient_id
  and target.spouse_patient_id is null;

-- Only the minimum linked identity needed by a patient-details screen.
create or replace function public.patient_spouse_summary(p_patient_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  caller_role text := public.current_app_role();
  spouse_id text;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
  if not (
    caller_role in ('receptionist', 'admin_manager', 'matron', 'chief_embryologist', 'lab_tech')
    or (caller_role = 'doctor' and public.doctor_has_patient_access(p_patient_id))
    or (caller_role = 'nurse' and public.nurse_has_patient_access(p_patient_id))
    or (caller_role = 'patient' and p_patient_id = public.current_patient_id())
    or (
      caller_role = ''
      and public.has_custom_permission('bio_details', 'view')
      and public.custom_role_scope_ok('bio_details', p_patient_id, null::uuid)
    )
  ) then
    raise exception 'not authorized to view spouse link' using errcode = '42501';
  end if;

  select bd.spouse_patient_id into spouse_id
  from public.bio_details bd where bd.patient_id = p_patient_id;
  if spouse_id is null then return null; end if;

  return (
    select jsonb_build_object(
      'patient_id', pn.patient_id,
      'full_name', pn.full_name,
      'dob', bd.dob,
      'sex', bd.sex,
      'blood_group', bd.blood_group,
      'status', bd.status
    )
    from public.patient_names pn
    join public.bio_details bd on bd.patient_id = pn.patient_id
    where pn.patient_id = spouse_id
  );
end;
$$;

revoke all on function public.patient_spouse_summary(text) from public, anon;
grant execute on function public.patient_spouse_summary(text) to authenticated;

-- Registration only offers patients who are not already connected to a
-- spouse, preventing accidental replacement of an established couple link.
create or replace function public.reception_spouse_directory(p_search text default '')
returns table(patient_id text, full_name text, dob date, sex text, spouse_patient_id text)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.current_app_role() not in ('receptionist', 'admin_manager') then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
  select pn.patient_id, pn.full_name, bd.dob, bd.sex, bd.spouse_patient_id
  from public.patient_names pn
  join public.bio_details bd on bd.patient_id = pn.patient_id
  where bd.spouse_patient_id is null
    and (p_search = '' or (pn.full_name || ' ' || pn.patient_id) ilike '%' || p_search || '%')
  order by pn.full_name;
end;
$$;

revoke all on function public.reception_spouse_directory(text) from public, anon;
grant execute on function public.reception_spouse_directory(text) to authenticated;

-- Allows a role to follow an explicit spouse link without making unrelated
-- patients visible. Lab staff receive only their existing restricted fields.
create or replace function public.linked_spouse_patient_detail(p_from_patient_id text, p_spouse_patient_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  caller_role text := public.current_app_role();
  is_linked boolean;
  is_authorized boolean;
begin
  select exists (
    select 1 from public.bio_details bd
    where (bd.patient_id = p_from_patient_id and bd.spouse_patient_id = p_spouse_patient_id)
       or (bd.patient_id = p_spouse_patient_id and bd.spouse_patient_id = p_from_patient_id)
  ) into is_linked;
  if not is_linked then raise exception 'patients are not linked spouses' using errcode = '42501'; end if;

  is_authorized := auth.uid() is not null and (
    caller_role in ('receptionist', 'admin_manager', 'matron', 'chief_embryologist', 'lab_tech')
    or (caller_role = 'doctor' and public.doctor_has_patient_access(p_from_patient_id))
    or (caller_role = 'nurse' and public.nurse_has_patient_access(p_from_patient_id))
    or (caller_role = 'patient' and p_from_patient_id = public.current_patient_id())
  );
  if not is_authorized then raise exception 'not authorized to follow spouse link' using errcode = '42501'; end if;

  if caller_role in ('lab_tech', 'patient') then
    return (
      select jsonb_build_object(
        'patient_id', pn.patient_id, 'first_name', pn.first_name,
        'surname', pn.surname, 'full_name', pn.full_name,
        'dob', bd.dob, 'sex', bd.sex, 'blood_group', bd.blood_group,
        'status', bd.status, 'spouse_patient_id', bd.spouse_patient_id
      )
      from public.patient_names pn join public.bio_details bd using (patient_id)
      where pn.patient_id = p_spouse_patient_id
    );
  end if;

  return (
    select to_jsonb(pn) || to_jsonb(bd)
    from public.patient_names pn join public.bio_details bd using (patient_id)
    where pn.patient_id = p_spouse_patient_id
  );
end;
$$;

revoke all on function public.linked_spouse_patient_detail(text,text) from public, anon;
grant execute on function public.linked_spouse_patient_detail(text,text) to authenticated;

-- Reception can confirm whether a portal login exists, but no password or
-- authentication secret is ever returned from the database.
create or replace function public.patient_front_desk_profile_v2(p_patient_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare result jsonb;
begin
  if public.current_app_role() not in ('receptionist', 'admin_manager') then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  select to_jsonb(pn) || to_jsonb(bd) || jsonb_build_object(
    'spouse_name', spouse_name.full_name,
    'portal_login_exists', exists (
      select 1 from public.profiles p where p.patient_id = pn.patient_id and p.role = 'patient'
    ),
    'portal_login_active', coalesce((
      select p.active from public.profiles p where p.patient_id = pn.patient_id and p.role = 'patient' limit 1
    ), false)
  ) into result
  from public.patient_names pn
  join public.bio_details bd on bd.patient_id = pn.patient_id
  left join public.patient_names spouse_name on spouse_name.patient_id = bd.spouse_patient_id
  where pn.patient_id = p_patient_id;

  return result;
end;
$$;

revoke all on function public.patient_front_desk_profile_v2(text) from public, anon;
grant execute on function public.patient_front_desk_profile_v2(text) to authenticated;

-- Keep the shared printable laboratory report supplied by the previous
-- migration synchronized with the expanded clinic identity.
create or replace function public.lab_result_report_context(p_result_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  caller_role text := public.current_app_role();
  result_patient_id text;
  report_context jsonb;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
  select lr.patient_id into result_patient_id from public.lab_results lr where lr.id = p_result_id;
  if result_patient_id is null then raise exception 'laboratory result not found' using errcode = 'P0002'; end if;
  if caller_role not in ('lab_tech', 'chief_embryologist', 'admin_manager')
     and not (caller_role = 'patient' and result_patient_id = public.current_patient_id()) then
    raise exception 'not authorized to view this laboratory report' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'clinic', jsonb_build_object(
      'clinic_name', cs.clinic_name, 'clinic_tagline', cs.clinic_tagline,
      'company_name', cs.company_name, 'company_address', cs.company_address,
      'city', cs.city, 'state', cs.state, 'country', cs.country, 'postal_code', cs.postal_code,
      'company_phone', cs.company_phone, 'company_phone_alt', cs.company_phone_alt,
      'company_email', cs.company_email, 'company_website', cs.company_website,
      'registration_number', cs.registration_number,
      'tax_identification_number', cs.tax_identification_number,
      'laboratory_license_number', cs.laboratory_license_number,
      'laboratory_director_name', cs.laboratory_director_name,
      'laboratory_director_title', cs.laboratory_director_title,
      'report_footer', cs.report_footer, 'logo_url', cs.logo_url
    ),
    'patient', jsonb_build_object(
      'patient_id', pn.patient_id, 'full_name', pn.full_name, 'dob', bd.dob, 'sex', bd.sex
    ),
    'result', to_jsonb(lr) || jsonb_build_object(
      'template_name', lt.name, 'entered_by_name', entered_by.full_name,
      'amended_by_name', amended_by.full_name
    )
  ) into report_context
  from public.lab_results lr
  join public.patient_names pn on pn.patient_id = lr.patient_id
  left join public.bio_details bd on bd.patient_id = lr.patient_id
  left join public.lab_templates lt on lt.id = lr.template_id
  left join public.profiles entered_by on entered_by.id = lr.entered_by_profile_id
  left join public.profiles amended_by on amended_by.id = lr.amended_by_profile_id
  cross join public.clinic_settings cs
  where lr.id = p_result_id and cs.id = 1;

  return report_context;
end;
$$;

revoke all on function public.lab_result_report_context(uuid) from public, anon;
grant execute on function public.lab_result_report_context(uuid) to authenticated;

commit;

select jsonb_pretty(jsonb_build_object(
  'clinic_document_columns_present', (
    select count(*) = 14 from information_schema.columns
    where table_schema = 'public' and table_name = 'clinic_settings'
      and column_name in (
        'clinic_tagline','company_phone_alt','company_email','company_website','city','state','country','postal_code',
        'registration_number','tax_identification_number','laboratory_license_number','laboratory_director_name','laboratory_director_title','report_footer'
      )
  ),
  'couple_registration_present', to_regprocedure('public.register_new_patient_with_partner(text,text,date,text,text,text,text,text,text,text,text,text,jsonb)') is not null,
  'spouse_summary_present', to_regprocedure('public.patient_spouse_summary(text)') is not null,
  'reception_spouse_directory_present', to_regprocedure('public.reception_spouse_directory(text)') is not null,
  'linked_spouse_detail_present', to_regprocedure('public.linked_spouse_patient_detail(text,text)') is not null,
  'front_desk_profile_has_login_status', position('portal_login_exists' in pg_get_functiondef('public.patient_front_desk_profile_v2(text)'::regprocedure)) > 0,
  'report_uses_complete_identity', position('laboratory_license_number' in pg_get_functiondef('public.lab_result_report_context(uuid)'::regprocedure)) > 0
)) as clinic_spouse_portal_verification;
